globalAuthorizer: ""
globalEndPointType: ""
globalVpc: ""
additionalResources:
  tokenTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TOKEN_TABLE}
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 2
  usersInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_USERS_INFO_TABLE}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 2
  usersReadyInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_USERS_READY_INFO_TABLE}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 2
customCapacities:
  - table: tokenTable
    read:
      minimum: 2
      maximum: 5
      usage: 0.75
    write:
      minimum: 2
      maximum: 5
      usage: 0.75
  - table: usersInfoTable
    read:
      minimum: 2
      maximum: 5
      usage: 0.75
    write:
      minimum: 2
      maximum: 5
      usage: 0.75
  - table: usersReadyInfoTable
    read:
      minimum: 2
      maximum: 5
      usage: 0.75
    write:
      minimum: 2
      maximum: 5
      usage: 0.75