globalAuthorizer: ""
globalEndPointType: ""
globalVpc: ""
additionalResources:
  tokenTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TOKEN_TABLE}
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  usersInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_USERS_INFO_TABLE}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  usersReadyInfoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_USERS_READY_INFO_TABLE}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
#  ipAuthTable:
#    Type: AWS::DynamoDB::Table
#    DeletionPolicy: Delete
#    Properties:
#      TableName: ${self:provider.environment.DYNAMODB_IP_AUTH_TABLE}
#      AttributeDefinitions:
#        - AttributeName: ip
#          AttributeType: S
#      KeySchema:
#        - AttributeName: ip
#          KeyType: HASH
#      ProvisionedThroughput:
#        ReadCapacityUnits: 1
#        WriteCapacityUnits: 1
customCapacities:
  - table: tokenTable
    read:
      minimum: 1
      maximum: 1
      usage: 0.75
    write:
      minimum: 1
      maximum: 1
      usage: 0.75
  - table: usersInfoTable
    read:
      minimum: 1
      maximum: 1
      usage: 0.75
    write:
      minimum: 1
      maximum: 1
      usage: 0.75
  - table: usersReadyInfoTable
    read:
      minimum: 1
      maximum: 1
      usage: 0.75
    write:
      minimum: 1
      maximum: 1
      usage: 0.75
